base/urls.py
from django.urls import path
from . import views 


urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),

    path('', views.home, name="home"),
   
    path('posts/', views.posts, name="posts"),
    path('post/<slug:slug>/', views.post, name="post"),
    path('profile/', views.profile, name="profile"),

    path('create_post/', views.createPost, name="create_post"),
    path('update_post/<slug:slug>/', views.updatePost, name="update_post"),
    path('delete_post/<slug:slug>/', views.deletePost, name="delete_post"),

    path('send_email/', views.sendEmail, name="send_email"),


  
]

stevekamworor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name




class Post(models.Model):
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True,blank=True, upload_to="images", default="placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)
    slug = models.SlugField(null=True, blank=True)
     
    def __str__(self):
        return self.headline
    
    def save(self, *args, **kwargs):
        if self.slug == None:
            slug = slugify(self.headline)

            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count +=1
                slug= slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()

            self.slug=slug
        super().save(*args, **kwargs)
    

base/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Post

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = '__all__'

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'tags':forms.CheckboxSelectMultiple(),
        }

    
    

base/views.py
from django.shortcuts import render, redirect   
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.mail import EmailMessage
from django.core.mail.backends import smtp

from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import render_to_string
from .models import Post
from .forms import PostForm,RegisterForm
from .filters import PostFilter
# Create your views here.

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user= form.save()
            auth_login(request, user)
            return redirect("home")
    context = {'form':form,}
    return render(request, 'base/register.html', context)

def login(request):
    context = {
    }
    return render(request, 'base/login.html', context)

def home(request): 
    posts = Post.objects.filter(active=True, featured=True)[0:3]
   


    context = {'posts':posts}
    return render(request, 'base/index.html', context) 

def post(request, slug):
    post = Post.objects.get(slug=slug)  
     
    context = {'post':post}
    return render(request, 'base/post.html', context)

def posts(request):
    posts = Post.objects.filter(active=True)
    myFilter = PostFilter(request.GET, queryset=posts)
    filtered_posts = myFilter.qs

    ordered_posts = filtered_posts.order_by('-created')


    paginator = Paginator(ordered_posts, 2)

    page = request.GET.get('page')

    try:
        paginated_posts = paginator.page(page)
    except PageNotAnInteger:
        paginated_posts = paginator.page(1)
    except EmptyPage:
        paginated_posts = paginator.page(paginator.num_pages)
    

    context = {'posts':paginated_posts,'myFilter':myFilter}
    return render(request, 'base/posts.html', context)
 
def profile(request):
    return render(request, 'base/profile.html') 
 
@login_required(login_url="home")
def createPost(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form':form}
    return render(request, 'base/post_form.html', context)

@login_required(login_url="home")
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')

    context = {'form':form}
    return render(request, 'base/post_form.html', context)


@login_required(login_url="home")
def deletePost(request,slug):
    post = Post.objects.get(slug=slug)

    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'item':post}
    return render(request, 'base/delete.html', context)


def sendEmail(request):

    if request.method == 'POST':

        template = render_to_string('base/email_template.html',{
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message'],
        })
        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['stevekamworor@gmail.com']
        )
        email.fail_silently=False
        email.send()

    return render(request, 'base/email_sent.html')
 

base/templates/base/delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="main-container">
	<form method="POST" action="">
		{% csrf_token %}

		<p>Are you sure you want to delete {{item}}?</p>
		<a class="btn btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
		<input class="btn btn-danger" type="submit" value="Confirm">
	</form>
</div>

{% endblock content %}

base/templates/base/email_sent.html
{% extends 'base/main.html' %}

{% block content %}

<style type="text/css">
	html, body{
		height: 100%;
	}

	#page-wrapper{
		height: 100%;
		display: flex;
		justify-content: center;
		align-items: center;
		text-align: center;
		background-color: #eaeaea;
	}

	#success-box{
		max-width: 800px;
		height: auto;
		background-color: #fff;
		border:1px solid #888;
		border-radius: 5px;
		padding: 15px;
	}

	#success-box p{
		font-size: 18px;
	}

</style>

<div id="page-wrapper">
	<div id="success-box" class="content-block">
		<h1>Thanks for reaching out!</h1>
		<p>Your message was successfully sent. I will do my best to get back to you in a timely manner :)</p>
		<a id="back-btn" class="btn btn-success" href="{% url 'home' %}">BACK TO HOME PAGE</a>
	</div>
</div>

{% endblock content %}

base/templates/base/email_template.html
{{message}}

{{name}}

{{email}}

base/templates/base/home.html
{% extends 'base/main.html' %}

{% block content %}


<h1>home page template</h1>

{% endblock %}

base/templates/base/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Steve Kimutai</title>
 
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
    <link id="theme-style" rel="stylesheet" type="text/css" href="">
   
</head>
<body>

    <section class="s1">
        <div class="main-container">
           <div class="greeting-wrapper">
                <h1>Hi, I'm Steve Kimutai</h1>
           </div>
           <div class="intro-wrapper">

            {% include 'base/navbar.html' %}
                

                <div class="left-column">
                     <img id="profile_pic" src="{% static 'images/office.jpg' %}" alt="profile_pic">
                     <h5 style="text-align: center; line-height: 0;">Personalize Theme</h5>

                     <div id="theme-options-wrapper">
                        <div data-mode="light" id="light-mode" class="theme-dot"></div>
                        <div data-mode="blue" id="blue-mode" class="theme-dot"></div>
                        <div data-mode="green" id="green-mode" class="theme-dot"></div>
                        <div data-mode="purple" id="purple-mode" class="theme-dot"></div>
                     </div>
                       <p id="settings-note">Theme settings will be saved for<br>your next visit</p>
                </div>
                <div class="right-column">

                     <div id="preview-shadow">
                        <div id="preview">
                            <div id="corner-tl" class="corner"></div>
                            <div id="corner-tr" class="corner"></div>
                            <h3>What I Do</h3>
                            <p>Recently finished campus and now I am a freelancer but looking to pursue my career goals </p>
                            <div id="corner-bl" class="corner"></div>
                            <div id="corner-br" class="corner"></div>
                        </div>
                    </div>
                </div>

           </div>
        
        </div>
    </section>

    <section class="s2">
        <div class="main-container">
            <div class="about-wrapper">
                <div class="about-me">
                    <h4>More about me</h4>

                    <p>I like creating new projects that solve the problems I see in my society .</p>

                    <p>Currently am working on a transport project to automate the process of moving small size goods all over the country.This will be available at the palm of your hands so long as you have a smart device</p>

                    
                <hr>
                <h4>TOP EXPERTISE</h4>

                <p>Full stack developer with primary focus on Django + React: <a target="_blank" href="{% static  'resume.pdf' %}">Download Resume</a></p>

                <div id="skills">
                    <ul>
                        <li>Python</li>
                        <li>Django</li>
                        <li>Javascript</li>
                        <li>React</li>
                        <li>Postgres</li>
                    </ul>
                    <ul>
                        <li>Google Maps API</li>
                        <li>JS Charts</li>
                        <li>Javascript</li>
                        <li>AWS (rds/s3)</li>
                        <li>Heroku</li>
                        <li>HTML/CSS</li>
                    </ul>
                </div>
                </div>
                <div class="social-links">
                     <img id="social_img" src="{% static 'images/linkedin.png' %}" alt="social-links">
                     <h3>Find me on linkedIn and Twitter</h3>

                     <a target="_blank" href="#">linkedIn: kamworor</a> <br>
                     <a target="_blank" href="#">Twitter: @skamworor</a>

                </div>

            </div>
        </div>
    </section>

    <section class="s1">
        <div class="main-container">
            <h3 style="text-align: center;">Some of my past Projects</h3>

            <div class="post-wrapper">
                {% for post in posts %}
              <div>
                    <div class="post">
                        <img class="thumbnail" src="{% static 'images/transport.png' %}" alt="post">
                        <div class="post-preview">
                            <h6 class="post-title">{{post.headline}}</h6>
                            <p class="post-intro">{{post.sub_headline}}</p>
                            <a href="{% url 'posts' %}">Read more</a>
                        </div>
                    </div>
              </div>
              {% endfor %}
              <div>
                    <div class="post"> 
                        <img class="thumbnail" src="{% static 'images/champ.jpg' %}" alt="post">
                        <div class="post-preview">
                            <h6 class="post-title">Post title</h6>
                            <p class="post-intro">This is a sentence. some more text</p>
                            <a href="#">Read more</a>
                        </div>
                    </div>
                </div>

                <div>
                    <div class="post">
                        <img class="thumbnail" src="{% static 'images/champ.jpg' %}" alt="post">
                        <div class="post-preview">
                            <h6 class="post-title">Post title</h6>
                            <p class="post-intro">This is a sentence. some more text</p>
                            <a href="#">Read more</a>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </section>

    <section class="s2">
        <div class="main-container">
            <h3 style="text-align: center;">Get in touch</h3>

            <form id="contact-form" action="{% url 'send_email' %}" method="POST">
                {% csrf_token %}
                <a href="" name="contact"></a>
                <label for="">Name</label>
                <input class="input-field" type="text" name="name">

                <label for="">Subject</label>
                <input class="input-field" type="text" name="subject">

                <label for="">Email</label>
                <input class="input-field" type="text" name="email">

                <label for="">Message</label>
               <textarea class="input-field" name="message" id="" ></textarea>

                 <input id="submit-btn" type="submit" value="send">
                 <button type="submit" class="btn btn-success">send</button>
            </form>


        </div>
    </section>
     
    <script type="text/javascript">
        let static = "{% static 'css' %}"
    </script>

    <script type="text/javascript" src="{% static  'js/script.js' %}"></script>

    
</body>
</html>

base/templates/base/login.html
{% extends 'base/index.html' %}
{% block title %}
Login
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <p>Already have an account? Login <a href="/login"></a></p> 

    <button type="submit" class="btn btn-success">login</button>
</form>
{% endblock %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Steve Kimutai</title>

	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-47692315-56');
	</script>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
</head>
<body>

	{% include 'base/navbar.html' %}


	{% block content %}
	<!-- Content goes here -->
	{% endblock content %}

</body>
</html>

base/templates/base/navbar.html
{% load static %}
<div class="nav-wrapper">

	<!-- Link around dots-wrapper added after tutorial video -->
	<a href="{% url 'home' %}">
		<div class="dots-wrapper">
			<div id="dot-1" class="browser-dot"></div>
			<div id="dot-2" class="browser-dot"></div>
			<div id="dot-3" class="browser-dot"></div>
		</div>
	</a>

	<ul id="navigation">
		<li><a href="{% url 'home' %}">contact</a></li>
		{% if request.user.is_authenticated %}
		   <li><a href="{% url 'create_post' %}">Create Post</a></li>
		{% endif %}

	</ul>
	

	

</div>


<script type="text/javascript">
	let menu = 'closed' 

	let menuIcon = document.getElementById('menu-icon')
	let navigation = document.getElementById('navigation')
	let closeBtn = document.getElementById('close-btn')

	menuIcon.addEventListener('click', toggleMenu)
	closeBtn.addEventListener('click', toggleMenu)


	function toggleMenu(){
		if (menu == 'closed'){
			navigation.style.display = 'block'
			closeBtn.style.display = 'block'
			menu = 'open'
		}else{
			navigation.style.display = 'none'
			closeBtn.style.display = 'none'
			menu = 'closed'
		}
	}

	    
	// Attaching the event listener function to window's resize event
	
	window.addEventListener("resize", function(){
		let width = document.documentElement.clientWidth;
		if(width > 1080){
				navigation.style.display = 'block'
		}else{
				navigation.style.display = 'none'
		}
		menu = 'closed'
		closeBtn.style.display = 'none'
	});
	
</script>

base/templates/base/post.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	img{
		max-width: 100%;
		object-fit: cover;
	}

	.featured_image{
		margin-top: 20px;
		margin-bottom: 20px;
	}

	.post-container{
			width: 900px;
			margin: 0 auto;
			padding-top: 20px;
			padding-bottom: 20px;
	}

	.comments-wrapper{
		margin-top: 50px;
		padding: 10px;
		border:1px solid var(--borderColor);
		-webkit-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		-moz-box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
		box-shadow: -1px 1px 3px -1px rgba(0,0,0,0.75);
	}

	.comment{
		display: flex;
		padding: 15px;
	}

	.comment-author{
		font-size: 14px;
		font-weight: 700;
		color: rgb(30, 174, 219) !important;
		margin: 2px;
	}

	.author-pic{
		width: 50px;
		height: 50px;
		border-radius: 50%;
		margin-right: 10px;
	}

	.comment-body{

		font-size: 14px;
	}

	@media screen and (max-width: 900px){
		.post-container{
			width: 95%;
		}
	}
</style>

<div class="post-container">

	<a class="btn btn-sm btn-primary" href="">&laquo Back to Posts</a>

	{% if request.user.is_staff %}
		 <a class="btn btn-sm btn-primary" href="">Edit</a>
		 <a class="btn btn-sm btn-danger" href="">Delete</a>
	{% endif %}

	<img class="featured_image" src="{{post.thumbnail.url}}">

	{% for tag in post.tags.all %}
		<span class="tag">{{tag}}</span>
	{% endfor %}
	<hr>

	<h1>{{post.headline}}</h1>
	<h4>{{post.sub_headline}}</h4>
	<br>

	<p>{{post.body|safe}}</p>

	<div class="comments-wrapper">
		<h5>Comments: {{post.postcomment_set.all.count}}</h5>
		<hr>
		<!--
			- Not logged in, output form and say "Register to comment and give room for a message"
			- When given username 
		-->
		{% if request.user.is_authenticated %}
		<form action="" method="POST">
			{% csrf_token %}
			<textarea required class="form-control" placeholder="Leave a comment..." name="comment"></textarea>
			<br>
			<input class="btn btn-info" type="submit" value="Submit">
		</form>
		{% else %}
			<p>Create an account to comment:</p>
			<a class="btn btn-primary" href="{% url 'register' %}">Register/Login</a>
		{% endif %}

		<hr>
		{% for comment in post.postcomment_set.all %}
			<div class="comment">
				<img class="author-pic" src="">
				<div>
					<p class="comment-author">{{comment.author}}: {{comment.created|date:"M-d-Y"}}</p>
					<p class="comment-body">{{comment.body}}</p>
				</div>
			</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

base/templates/base/post_form.html
{% extends 'base/main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
	#div_id_tags > div{
		max-height: 100px;
		overflow-y: scroll;
		border:1px solid #888;
		padding: 5px;
		border-radius: 5px;
	}
</style>
<div class="main-container">
	<a class="btn btn-sm btn-primary" href="{% url 'posts' %}">&laquo Back to Posts</a>
	
	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.media}}
		{{form|crispy}}
		<input class="btn btn-primary" type="submit" value="Submit Post">
		
	</form>
</div>

{% endblock content %}

base/templates/base/posts.html
{% extends 'base/main.html' %}
{% load static %}
{%  load crispy_forms_tags %}
{% block content %}


<style type="text/css">
	#div_id_tags, #id_tags{
		overflow-y: scroll;
		max-height: 100px;
		border-radius: 5px;
		padding: 5px;
		border:1px solid #888;
	}
	.tag{
    display: inline-block;
    color: #fff;
    background-color: #888;
    border-radius: 5px;
    margin: 2px;
    padding: 2px 5px;
    font-size: 12px;
}
</style>

<div class="main-container">
	<h1>Posts</h1>
	<form id="searchForm" method="GET">
		{{myFilter.form | crispy}}
		<br>
		<input class="btn btn-primary" type="submit" value="search">

	</form>
	
	<div class="post-wrapper">

		{% for post in posts %}
		<div>
			<div class="post">
				<img class="thumbnail" src="{{post.thumbnail.url}}">
				<div class="post-preview">
					<h6 class="post-title">{{post.headline}}</h6>
					<br>
					<p class="post-intro">{{post.sub_headline}}</p>
					<a href="{% url 'post' post.slug %}">Read More </a>

					{% if request.user.is_authenticated %}
					| <a href="{% url 'update_post' post.slug %}">Edit </a>
					| <a href="{% url 'delete_post' post.slug %}">Delete </a>
					{% endif %}
                      <hr>
				
					{% for tag in post.tags.all %}
						<span class="tag">{{tag}}</span>
					{% endfor %}
					<hr>
				</div>
			</div>
		</div>
		{% empty %}
			<h3>No posts found...</h3>
		{% endfor %}
	</div>
     <div class="row">
		{% if posts.has_other_pages %}
            <ul class="pagination">
				 
				{% if posts.has_previous %}
				  <li class="page-item"><a data-page="{{posts.previous_page_number}}" href="?page={{posts.previous_page_number}}" class="page-link">&laquo;</a></li>

				  <li class="page-item"><a data-page="1" href="?page=1" class="page-link">First</a></li>
				{% endif %}


                {% for i in posts.paginator.page_range %}
				  {% if posts.number == i %}
                  <li class="page-item"><a class="active page-link">{{i}}</a></li>
				  {% else %}
				  <li class="page-item"><a data-page="{{i}}" href="?page={{i}}" class="page-link">{{i}}</a></li>
				  {% endif %}
				{% endfor %}

				{% if posts.has_next %}
				<li class="page-item"><a data-page="{{posts.paginator.num_pages}}" href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>

				<li class="page-item"><a data-page="{{posts.next_page_number}}" href="?page={{posts.next_page_number}}" class="page-link">&raquo;</a></li>
				{% endif %}
			</ul>
		{% endif %}

	 </div>
</div>

<script type="text/javascript">
	let searchForm = document.getElementById('searchForm')
	let pageLinks = document.getElementsByClassName('page-link')

	for(var i=0; pageLinks.length; i++){
		pageLinks[i].addEventListener('click', function(e){
			e.preventDefault()
			let page = this.dataset.page
			console.log('page:', page)
			searchForm.innerHTML += `<input value="${page}" name="page" hidden>`
			searchForm.submit()
		})
	}

</script>

{% endblock content %}

base/templates/base/register.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}



<form action="" method="POST">
    {% csrf_token %}
    {{form|crispy}}

    <p>Already have an account? Login <a href="/login">Here</a>!</p>

    <button type="submit" class="btn btn-success">register</button>
</form>
{% endblock %}